### ISSUE TITLE
Question about vcm_tab_complete

### ISSUE THREAD

**Issue by ajpaulson** [ajh17/VimCompletesMe#11]
Does the `b:vcm_tab_complete` option only take one argument or can I set a comma separated list in the order that I prefer?

for example:
`let b:vcm_tab_comlpete = "tags, user, omni"`

**Comment by ajh17** [comment]
Sorry, but for now, it will only work with one argument. 

A nice idea though, I will see (or PRs welcome!) if I can make this happen. A workaround now is if any of those completions gets no results, you can press Tab again, and VimCompletesMe will automatically switch to Keyword completion instead.
