### ISSUE TITLE
compatibility with neosnippet

### ISSUE THREAD

**Issue by sunaku** [ajh17/VimCompletesMe#12]
After expanding a snippet in [neosnippet](https://github.com/Shougo/neosnippet.vim), pressing TAB doesn't take me to the next snippet placeholder.  Instead, it triggers this plugin's response and destroys the productivity benefits of snippet expansion. :scream:

Could you suggest a way to make this plugin and neosnippet play well together?  Thanks! :sweat_smile:

**Comment by ajh17** [comment]
Hi, 

Unfortunately, mapping `<Tab>` in insert mode to two different plugins does not work very well. 

So the solution is that you can either use a different shortcut for VimCompletesMe, (see the `:help vcm_default_maps` option), or you can choose new backward and forward triggers for neocomplete (something like `C-j` or `C-k`).

**Comment by sunaku** [comment]
:+1: Thanks, I followed your tip and solved the issue like this:  

```diff
 " SuperTab like snippets behavior (but yield to neocomplete)
 imap <expr><Tab> pumvisible() ?
-      \ "\<C-n>" :
+      \ "\<Plug>vim_completes_me_forward" :
       \     neosnippet#expandable_or_jumpable() ?
       \     "\<Plug>(neosnippet_expand_or_jump)" :
       \ "\<Tab>"
 smap <expr><Tab> neosnippet#expandable_or_jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)"
  \: "\<Tab>"
```

I also had to disable the default VimCompletesMe mappings:

```vim
" see neosnippet configuration for <Tab> map
let g:vcm_default_maps = 0
imap <S-Tab> <Plug>vim_completes_me_backward
```

Cheers. :sweat_smile:

**Comment by ajh17** [comment]
@sunaku Nice, thanks! I should add this in the FAQ.
