### ISSUE TITLE
Is there any way to configure <CR> to trigger completion?

### ISSUE THREAD

**Issue by jordwalke** [ajh17/VimCompletesMe#13]

**Comment by sunaku** [comment]
```vim
imap <CR>   <plug>vim_completes_me_forward
```

**Comment by ajh17** [comment]
Yep, just as @sunaku said.

If you want `<CR>` to select a completion entry instead, you can map CR to: 

`inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"`
