### ISSUE TITLE
Use VimCompletesMe with emmet-vim

### ISSUE THREAD

**Issue by ushu** [ajh17/VimCompletesMe#14]
Hello guys,

when I use the plugin with emmet-vim (with tab-based completion configured for emmet-vim), it seems that VimCompletesMe overrides the emmet bindings for <tab>.

Any idea on what could be the cause ?

(btw the plugin is very usefull in all other contexts, thx !!!)

**Comment by ajh17** [comment]
Hi, any chance you have emmet-vim set up to use Tab for expansion? If so, you can try setting a different key to expand, either in VimCompleteMe or in emmet-vim.
