### ISSUE TITLE
default filetype  vcm_omni_pattern

### ISSUE THREAD

**Issue by Konfekt** [ajh17/VimCompletesMe#22]
Instead of a too coarse `g:vcm_omni_pattern` (that mingles different progamming languages), VimCompletesMe should provide for the convenience of the user, for the most important FileTypes, sensible `b:vcm_omni_pattern` such as
```vim
augroup VimCompletesMe
    autocmd!
    autocmd FileType vim let b:vcm_omni_pattern = '\v\k+$'
augroup END
```

**Comment by ajh17** [comment]
I think a global `vcm_omni_pattern` is useful to have anyway just because new languages that come out that use similar omni patterns as c/c++ can get that omnicompletion support right away. 

I do agree that we should introduce a local `vcm_omni_pattern`. I think your #21 PR takes care of this.

**Comment by Konfekt** [comment]
Yep. It does.
