### ISSUE TITLE
auto close preview window after completion

### ISSUE THREAD

**Issue by tnguyen14** [ajh17/VimCompletesMe#29]
Is there a way to auto-close the preview window after completion?

**Comment by ajh17** [comment]
Just to be clear, the preview window is not a VimCompletesMe feature. The preview window is part of Vim itself (`:help preview-window). Moreover, VimCompletesMe does not manually show preview window. It's controlled by the 'completeopt' setting in Vim (`:help completeopt`).

So, if you were asking in general, you could modify the `completeopt` setting, or you could write an auto command something like this and put in in your ~/.vimrc to automatically close it if you leave insert mode:

`autocmd InsertLeave * if bufname('%') != "[Command Line]" | pclose | endif`

I will close this issue though, as this feature is provided by Vim and VCM does not change the preview window in any way.

**Comment by tnguyen14** [comment]
Hi, was just wondering, is there a way to modify `completeopt` setting to do this?

**Comment by ajh17** [comment]
@tnguyen14 Unfortunately, no. It'd be a nice feature to ask from the Vim developers though: https://github.com/vim/vim/issues
