### ISSUE TITLE
Not doing anything on tab

### ISSUE THREAD

**Issue by kasbah** [ajh17/VimCompletesMe#33]
I just installed this using pathogen. When I press tab in any file it just inserts spaces like the plugin isn't doing anything. I just uninstalled YouCompleteMe and was expecting a similar behaviour on tab to that. Am I wrong about that?

`:echo g:loaded_VimCompletesMe` does return a `1` and I don't see any error messages.

**Comment by ajh17** [comment]
Hi,

Where are you specifically using Tab?

If you use Tab on the start of the line, VimCompletesMe will indent. If you use it when typing a word, then you will get completions. 

Is that what you're seeing?

**Comment by kasbah** [comment]
Hi! No, yes, sorry, after typing bits of a word that I think it should complete. I have been using YouCompleteMe and was expecting similar behaviour as that but am only getting spaces.

**Comment by ajh17** [comment]
Yeah, VimCompletesMe is manually invoked. It differs from YouCompleteMe in that way.

Personally, I like manually invoked completion engines, thus VimCompletesMe was created in that way.

**Comment by kasbah** [comment]
So, you are saying it's working as intended and nothing is supposed to happen on tab? How do I use it then?

**Comment by ajh17** [comment]
Yeah it sounds like it.

Vimcompletesme should work like below:

1. If you're at the beginning of the line, hitting tab will insert tab/spaces to indent
2. If you're typing a word and hit tab, hitting Tab will try to complete that word
3. If you're at the beginning of the line, hitting Shift+Tab will deindent.

**Comment by kasbah** [comment]
I am saying 2 isn't working at all. I'll try disabling all my other plugins when I next get a chance.

**Comment by ajh17** [comment]
@kasbah: Ah okay, if you can, can you tell me the output for the following command:

`:verbose imap <Tab>`

**Comment by kasbah** [comment]
I did a bit of a clear out of my `.vim` folder did a fresh install of Pathogen and copied all my pathogen plugins and the `colors` folder. I had some remnants of things hanging around before I started using Pathogen. It works fine now. I can't really be bothered to find out what was conflicting but I'll keep an eye on it in case I install/re-install something new does conflict.

**Comment by ajh17** [comment]
Cool, thanks for the follow up, glad cleaning up solved your problem!

**Comment by adrianoviana87** [comment]
> @kasbah: Ah okay, if you can, can you tell me the output for the following command: `:verbose imap <Tab>`

Thanks. That helped me. I was having the same issue. It happens that ultisnips was using the TAB key.
so I mapped it to a different to `<c-s>`
```
let g:UltiSnipsExpandTrigger="<c-s>"
```
