### ISSUE TITLE
Settting vcm_tab_complete to 'dict' does not work.

### ISSUE THREAD

**Issue by talha131** [ajh17/VimCompletesMe#34]
This my vimrc file.

```ruby
    if (has('mac'))
        setlocal dictionary=/usr/share/dict/words 
        autocmd FileType markdown let b:vcm_tab_complete = 'dict'
    endif
```

From [docs](https://github.com/ajh17/VimCompletesMe/blob/master/doc/VimCompletesMe.txt#L66-L70),

> 
    autocmd FileType text,markdown let b:vcm_tab_complete = 'dict'

and 

> NOTE: The "dict" option requires the user to set |'dictionary'| in their
|vimrc| file. In Unix, you can put the following in your ~/.vimrc:
>
    set dictionary=/usr/share/dict/words

As you can see I have set the dict.

But VimCompletesMe does not offer tab completion from dictionary. Even though CtrlX+CtrlK works fine.

Here is a demo

[![asciicast](https://asciinema.org/a/8l89huexx5b6xdd16plt7obhv.png)](https://asciinema.org/a/8l89huexx5b6xdd16plt7obhv)

**Comment by ajh17** [comment]
Thanks for the report!

Actually what happened is that there's a much better built in setting to control this, so VimCompletesMe doesn't need that 'dict' option anymore.

What you can do is set Vim's `'complete'` option to add the 'k' flag like so:

autocmd FileType text,markdown setlocal complete+=k

The docs should be updated, you are right! I will update them now.

**Comment by ajh17** [comment]
I updated the doc in commit 426d4b46.

Let me know if you get it working!

**Comment by talha131** [comment]
@ajh17 Thank's a lot. It worked.
