### ISSUE TITLE
Confusion about "tags" as a b:vcm_tab_complete value

### ISSUE THREAD

**Issue by thoughton** [ajh17/VimCompletesMe#35]
Hi,

I'm a new user, using this plugin in conjunction with vim-gutentags, primarily for C and C++ work.

Firstly I'd like to say this combination of plugins has been far easier to setup than any other solution I've tried in the past, so thank you!

However, I've come across some slight confusion in the docs.  In the `b:vcm_tab_complete` section I found the following:
```
The b:vcm_tab_complete makes a great :autocmd as follows:

    autocmd FileType ruby let b:vcm_tab_complete = "tags"
```
But nowhere else in the docs (including the paragraphs directly above where this quote came from) does it list `"tags"` as a valid setting for the `b:vcm_tab_complete` variable.

Is this potentially just outdated documentation? Or is there still a situation when `"tags"` is a useful and valid setting?

(As an aside, after reading through vim's own docs, I'm wondering whether for C and C++ that "omni" completion is usually better than "tag" completion anyway, as I think that is more sensitive to context, which is helpful for completing member variables and so on? So perhaps for `FileType c,cpp` I should just be setting `b:vcm_tab_complete = "omni"` anyway?)
 
Thanks again for a great plugin!

**Comment by ajh17** [comment]
Yes sorry about that, the docs were referencing the tags option that is no longer there in the current version.

The reason for this is that, it's much easier to use the omnicomplete for the language provided by Vim, as you mentioned. If you need tags to be included in the completion, you can set Vim's own `'complete'` variable:

`set complete+=t`

However, if you read `:help 'complete'`, it suggests that 't' (tags) is already included by default, so just by using this plugin, the Tab key should offer completion from tags already.

You don't need to manually set "omni" for the `b:vcm_tab_complete` variable either. VimCompletesMe will automatically switch to omni completion mode for C/C++ if you typed a `->` or `.` after a word and then invoke Tab. If you would prefer VimCompletesMe to *always* offer omnicompletion, then you might want to set the "omni" setting.

I hope that the explanation makes sense. I'll overhaul the documentation shortly. 

Thanks!

**Comment by thoughton** [comment]
That's great, thank you for the quick and informative reply!
