### ISSUE TITLE
Have subsequent <Tab> key presses continue to go up from the bottom

### ISSUE THREAD

**Issue by Asheq** [ajh17/VimCompletesMe#36]
With this plugin, the first time you press `<Tab>`, it goes to the bottom of the completion list (as if `<C-p>` was invoked). This is fine (I understand the reasoning behind this is that the bottom of the list is the closest match behind to the cursor as mentioned in the FAQ).

However, if I want to continue to go upwards from the bottom of the list (as if I pressed `<C-p>` again), I have to press `<S-Tab>`. I would rather continue pressing `<Tab>`. Is there anyway I can continue to press `<Tab>` to go upwards?

This line doesn't quite do that, because it starts off at the top before going up.

    let g:vcm_direction = 'p'

**Comment by Asheq** [comment]
Changing this line

    return a:shift_tab ? dirs[!dir] : dirs[dir]

to

    return a:shift_tab ? dirs[dir] : dirs[!dir]

does the trick. Not sure the best way to make this an option though.

I'm also having second thoughts about whether I want this. May be someone can convince me one way or the other.

**Comment by ajh17** [comment]
This looks like a duplicate of #7. Can you look through that issue and clarify that you still have an issue?

**Comment by Asheq** [comment]
Yeah, it is. I will close this. Like @lowmanb94 I wanted to have `<Tab>` presses always invoke `<C-p>` (even when the popup is open) and `<S-Tab>` always invoke `<C-n>`. However, after a little reflection, I think this might be disorienting. I'll try the default behavior of this plugin for a while and see how I like it.

I think what what would be ideal, is if Vim itself had an option to display a completion popup where the _top_ of the menu is the closest match searching backwards from the _cursor_. There doesn't currently seem to be that option.
