### ISSUE TITLE
Showing suggestion without pressing any key

### ISSUE THREAD

**Issue by vortexnix** [ajh17/VimCompletesMe#37]
I am transitioning from YCM to VCM. Is there a setting to show suggestions automatically without the need to press Tab key. In YCM there is no need to press tab for showing the suggestions. Kindly help. Thanks

**Comment by ajh17** [comment]
@vortexnix: VCM and YCM differ in that VCM is a manual invocation of the completion suggesstions whereas YCM is automatic. VCM also leverages built in completion options available in Vim.

As such, there's not an automatic invocation option for VCM.

**Comment by vortexnix** [comment]
Got it. Thanks for your reply @ajh17 
Very nice plugin.
