### ISSUE TITLE
Doesn't Work Out of the Box

### ISSUE THREAD

**Issue by fuzzybear3965** [ajh17/VimCompletesMe#38]
I've installed your plugin and confirm that it's within my runtimepath. However, in contexts where (in insert mode) <kbd>Ctrl</kbd><kbd>x</kbd><kbd>Ctrl</kbd><kbd>o</kbd> renders a dropdown of relevant matches, <kbd>Tab</kbd> does nothing but insert a tab character into my document. I haven't tried using it with an empty vimrc file, but I see no other <kbd>Tab</kbd> mapping. Could you give me a hand working through some diagnostics?

**Comment by ajh17** [comment]
Can you provide more information? For example, after what character are you pressing Tab? What filetype are you trying it on, what is the value of running `:echo b:vcm_tab_complete`?

**Comment by fuzzybear3965** [comment]
I can definitely provide more information. Thanks for your questions.

1) I'm pressing the "tab" key (above <kbd>caps</kbd> on a normal keyboard).
2) I'm trying it on filetype `tex`.
3) `:echo b:vcm_tab_complete' returns 
```
E121: Undefined variable: b:vcm_tab_complete
E15: Invalid expression: b:vcm_tab_complete
```
I was operating under the instructions in that (in insert mode)

```
Without any configuration, the Tab key will, depending on the context, offer:

Vim's local keyword completion (Ctrl-X_Ctrl-N)
File path completion when typing a path (Ctrl-X_Ctrl-F)
Omni-completion after typing a period or an arrow operator (Ctrl-X_Ctrl-O).
```

So, if <kbd>ctrl</kbd><kbd>x</kbd><kbd>ctrl</kbd><kbd>o</kbd>

**Comment by ajh17** [comment]
Thanks, can you also provide the output of `set omnifunc?`? Please include the question mark after omnifunc.

Also for the first question, I meant, after what character in your text file are you pressing Tab? For example, are you pressing Tab after a period or some thing else?

**Comment by fuzzybear3965** [comment]
`set omnifunc?` returns (for the LaTeX file that I'm working on using the [vimtex](http://github.com/lervag/vimtex) plugin) `omnifunc=vimtex#complete#omnifunc`.

I'm sorry that I misread your earlier question with regards to "when" I'm pressing <kbd>Tab</kbd>. I am pressing <kbd>Tab</kbd> after a `{`. For context, I am trying to use the omnifunc to complete a file name for a LaTeX `\includegraphics{file_name_here}` directive. More context is given below.
```
\begin{figure}[h]
   \centering
   \includegraphics[width=0.8\linewidth]{}
   \caption{Some }
   \label{fig:some}
\end{figure}
```
I navigate to the empty curly braces on the third line and press <kbd>Tab</kbd>. Nothing happens.
I navigate to the empty curly braces on the third line and press <kbd>Ctrl</kbd><kbd>x</kbd><kbd>Ctrl</kbd><kbd>o</kbd> and I get a list of the picture files whose file names can be inserted within that context.

**Comment by ajh17** [comment]
Ahh okay great. Currently, the plugin only invokes omni completion if there's a `.` or `->` (for C/C++/Python/Ruby, etc) filetypes. I can add a `{` for Latex to also invoke omnicompletion.

Not being familiar with latex, is the `{` the only operator for which you want omnicompletion or do you also want it for `\`?

**Comment by fuzzybear3965** [comment]
Oh, okay. I guess that's what this part of the documentation means:
```
                                                         *'g:vcm_omni_pattern*
Values: string                                                               ~
Default: '\v(\.\|->\|::)'                                                    ~

The global pattern after which VimCompletesMe triggers Omni-completion.
```
I tried setting the buffer-local variable `b:vcm_omni_pattern` using
`:let b:vcm_omni_pattern="{"` within the active LaTeX buffer (no after file, yet). I made sure that variable had the proper value by `:echo b:vcm_omni_pattern="{"` -> `{`.

<kbd>Tab</kbd> within the empty curly braces still fails to load the dropdown.

**Comment by ajh17** [comment]
Hmm, that's interesting. I'm not too familiar with latex so I apologize if I try something incorrectly. So I tried to get vimtex installed on my system along with latexmk/latex.

After I opened a test.bib file, I invoked `:let b:vcm_omni_pattern='{'` and VCM invoked omni completion for me. However, I think because I don't have something configured, vimtex just threw errors for me. But it does confirm that VCM will invoke Ctrl-X Ctrl-O completion after a brace if you change the `b:vcm_omni_pattern` variable.

**Comment by fuzzybear3965** [comment]
That's strange. Are the errors that vimtex is reporting related to the omnicompletion function?

I'm using it on a LaTeX filetype. You can go ahead and use the below file for testing purposes. Its extension is `.tex`.

```latex
\documentclass{article}
\begin{document}
\begin{figure}[h]
\includegraphics[width=0.8\linewidth]{}
\end{figure}
\end{document}
```

**Comment by ajh17** [comment]
I get the following errors if I create a test.tex using your provided text:

<img width="690" alt="screen shot 2017-02-27 at 21 57 34" src="https://cloud.githubusercontent.com/assets/1159146/23393464/deaf1116-fd37-11e6-868c-41b4e7912f85.png">

But, this does confirm that VCM is invoking ctrl-x ctrl-o completion for me if I press Tab after typing a `{`

**Comment by fuzzybear3965** [comment]
Okay, we're getting closer. I disabled Ultisnips (which *was* enabled to expand tab to some filetype-based snippet). My bad :/. I was a bit lazy in doing my homework beforehand.

`:imap <Tab>` returns `<Plug>vim_completes_me_forward`. Now, setting the vcm_omni_pattern to { *does* trigger a completion. However, it triggers a "File name completion (^F^N^P)", ctrl-x ctrl-f, not an omni completion, ctrl-x ctrl-o.

**Comment by ajh17** [comment]
Okay, great, no worries, in that case it makes sense.

So I'm guessing you're on Windows, correct?

**Comment by fuzzybear3965** [comment]
Yeah, I'm on Windows 10.

Are you saying the behavior I'm experiencing is consistent with what you'd expect? If so, why would I be triggering file name completion instead of omni completion?

**Comment by ajh17** [comment]
Nope, I meant I know what the issue is. What's happening is that VCM checks text before the cursor. So it's seeing the \ you typed in the current line, and thus offers file completion instead instead of omni completion.

I can fix this by updating VCM. Give me a day or two to test on a Windows machine (I don't have one) and I'll let you know.

Thanks for opening this issue!

**Comment by fuzzybear3965** [comment]
No stresses, my main man. Let me know if you want me to run any tests. Thanks for being understanding of some of the (avoidable) delays in diagnosing this issue.

I'm excited to use your plugin for realsies.

**Comment by ajh17** [comment]
Can you pull the latest plugin update? I believe this should resolve your issue.

Thanks!

**Comment by fuzzybear3965** [comment]
Yep! Thanks @ajh17.

**Comment by ajh17** [comment]
Great!
