### ISSUE TITLE
Wrong context on trigger

### ISSUE THREAD

**Issue by fuzzybear3965** [ajh17/VimCompletesMe#39]
Hey, @ajh17, this is related to the issue I was having before. I am trying to trigger omni completion in an environment where VimCompletesMe is performing file name completion. This is happening inside of `{}`s in `\cite{}` in LaTeX documents. As a test case you can use the following file.

```latex
\documentclass{article}
\begin{document}

\cite{}

\begin{thebibliography}
   \bibitem{latexcompanion} 
   Michel Goossens, Frank Mittelbach, and Alexander Samarin. 
   \textit{The \LaTeX\ Companion}. 
   Addison-Wesley, Reading, Massachusetts, 1993.
\end{thebibliography}

\end{document}
```

**Comment by ajh17** [comment]
Hmm it seems to work for me. VCM is invoking Omni completion, not file completion for me. But I detect that this may be again a Windows problem. 

Are you using let b:vcm_omni_pattern="{"? It might also be useful to add in a "\" there so it continues to use omni completion for this.

For example: `let b:vcm_omni_pattern="{\|\\"`

**Comment by fuzzybear3965** [comment]
I suck. Adding `let b:vcm_omni_pattern="{"` fixed all.

I didn't have that in my vimrc file since our last interaction. I just applied that setting on a per-buffer basis. Now, it's in my vimrc file. We should be okay.

**Comment by ajh17** [comment]
Okay, great. No worries.
