### ISSUE TITLE
Retrying VCM in certain contexts triggers different types of completion

### ISSUE THREAD

**Issue by fuzzybear3965** [ajh17/VimCompletesMe#40]
This is related to #39. I have noticed that triggering VCM in the `\cite{}` context triggers omni-func completion. That's perfect. However, if I 1) select a match for that `\cite{}` (say `\cite{some_match}`, for example) and then I 2) `di{` to clear the contents between the curly braces of `\cite{some_match}` and then I 3) try to use VCM *again* between those curly braces then keyword local completion is triggered. So, I get omni-completion the first time (inside the curly braces). Upon subsequent attempts at trying to re-use omni-completion in that context I don't get omni-completion, I get keyword local completion.

I hope that that makes sense.

**Comment by ajh17** [comment]
Yes I can reproduce this. I'll fix this shortly.

**Comment by ajh17** [comment]
Thanks for bringing up this issue!

Fallback completion should work much better and you should always get omni completion now after the `{` provided that you have added that into `b:vcm_omni_pattern`. 

Let me know if it works for you! :smile:

**Comment by fuzzybear3965** [comment]
> Thanks for bringing up the issue!

Well my pleasure! Thanks for your time and effort(s).

> Let me know if it works for you!

We look golden!
