### ISSUE TITLE
Does not complete correctly with completeR omnifunc

### ISSUE THREAD

**Issue by zippeurfou** [ajh17/VimCompletesMe#43]
Hi,
I have been reading [this issue](https://github.com/ajh17/VimCompletesMe/issues/38) and I believe my issue is quite similar.
I am using the plugin [nvim-R](https://github.com/jalvesaq/Nvim-R) that allows omnicompletion to be able for R language which give me `set omnifunc=CompleteR`.
Here are what "should" trigger the omnicompletion `'::', '$', '@'`. However so far only `::` does it.
Additionally, the omnicompletion do not get triggered when I start typing a word that could be omnicompleted (such as `su` that should be completed to `sum` for example).
Also, `:echo b:vcm_tab_complete` returns
```
E121: Undefined variable: b:vcm_tab_complete
E15: Invalid expression: b:vcm_tab_complete
```
And when I did on my console `set b:b:vcm_tab_complete="$"` it did work for completing `$`.
Note that `ctrlx ctrlo` works perfectly in all cases.

I tried to look at the resolution of the issue but I am on Mac os x using `vim-plug` and I don't have such path: `~/.vim/after`. Not sure if I can just create the folder or if my `.vimrc` needs to be edited as well.
Additionally, I'd like for vimcompletesme to do it every time it sees `CompleteR` omnifunc as it is on several different filetypes.

**Comment by ajh17** [comment]
Hi!

If you would like to add characters to trigger omnicompletion, you can add this to the `g:vcm_omni_pattern` variable. See the help docs for it:   `:help :g_vcm_omni_pattern`

For your second question, you don't have to touch the `b:vcm_tab_complete` variable. It should just all work after setting the aforementioned `g:vcm_omni_pattern` variable. Also, see the help docs for `:help b:vcm_tab_complete`. It only takes "user", "vim", and "omni" as values, not "$".

**Comment by zippeurfou** [comment]
Thank you @ajh17 for the quick answer.
I think it was a typo and I meant `g_vcm_omni_pattern`
Two quick questions (because I don't know much).
1. Can I make the `g_vcm_omni_pattern` completion conditional on `set omnifunc=CompleteR`? Therefore I don't have the omni completion after `$` in other language that could mean something else.
2. if I want to add ` '$', '@'` is this the code I should be adding?
```
let b:vcm_omni_pattern="$"
let b:vcm_omni_pattern="@"
``` 
I am not sure how variable works in vi 😞

**Comment by ajh17** [comment]
Yes, but the easiest way is you set it only for the R programming language. You can do so by:
    a. Adding the following to your ~/.vimrc:
    `autocmd Filetype r let b:vcm_omni_pattern="\k\+\(::\|\$\|@\)\k*$"`
    OR
    b. Creating a new file inside ~/.vim/after/ftplugin called "r.vim" and putting the following inside it:
    `let b:vcm_omni_pattern="\k\+\(::\|\$\|@\)\k*$"`


The above will let you omni complete with `$`, `@`, and `::` in R. Let me know if you have any further questions 😄

**Comment by zippeurfou** [comment]
@ajh17 thank you.
just tried the solution a. It does not seems to work.
Here is `echo vcm_omni_pattern`
<img width="493" alt="screen shot 2017-06-11 at 3 54 38 pm" src="https://user-images.githubusercontent.com/4520383/27014040-64f7fe2c-4ebe-11e7-87c8-9a53fdcb437b.png">
Here is `su` + `ctrl x` + `ctrl o`
<img width="401" alt="screen shot 2017-06-11 at 3 55 53 pm" src="https://user-images.githubusercontent.com/4520383/27014059-d254f128-4ebe-11e7-88a2-52ea34ec545c.png">
And here is the same with tab:
<img width="248" alt="screen shot 2017-06-11 at 3 58 06 pm" src="https://user-images.githubusercontent.com/4520383/27014060-dc4e6a2e-4ebe-11e7-8fe9-7f32a8e1f54f.png">

**Comment by ajh17** [comment]
@zippeurfou: Yep, just set this in your ~/.vimrc:

`autocmd FileType r let b:vcm_tab_complete = "omni"`

**Comment by zippeurfou** [comment]
Wow this is so perfect!
Thank you a lot!

**Comment by ajh17** [comment]
No problem!
