### ISSUE TITLE
After add the mapping about the Enter key,  vim will blocked when add a new line in insert mode.

### ISSUE THREAD

**Issue by lishuoxi** [ajh17/VimCompletesMe#5]
After I add the mapping just as the doc said.  My vim will blocked when I type Enter key in insert mode. So is there other way to select the popup menu item ??  Or  is it just my problem?

**Comment by ajh17** [comment]
Hi, it seems that you may have a <CR> mapping already defined. 

Can you check the output of  `:verbose imap <CR>`

You can also select the popup menu item by hitting `Ctrl-y`

**Comment by ajh17** [comment]
My mistake, the problem is on my end. Thanks for catching it!

**Comment by lishuoxi** [comment]
thank you for your good work.  The script suits me very well. ^-^

**Comment by ajh17** [comment]
Thanks so much! I'm glad you like it. :grinning:
