### ISSUE TITLE
How does this compare to Completor.vim?

### ISSUE THREAD

**Issue by tuyenpm9** [ajh17/VimCompletesMe#57]
I'm considering to switch to more minimal completion plugin, currently use completor with depend on builtin-python.

So how does this compare to Completor? https://github.com/maralla/completor.vim

**Comment by ajh17** [comment]
I haven't used completor but VCM is just minimally adds on top of Vim's built in completion features. So pressing Tab will give you the (most of the time) correct completion type described in `:help ins-completion`. It doesn't, nor will it ever, strive to do anything else. If you want more features than what built in Vim offers, look for a different completion plugin.

VCM is meant to be very minimal. But you can make your own mind on what you like. Maybe try installing one over the other and see what you like best. Ultimately, it's up to you.

Hope this helps.
