### ISSUE TITLE
How to have this plugin support Ultisnips?

### ISSUE THREAD

**Issue by tuyenpm9** [ajh17/VimCompletesMe#58]
I've noticed this plugin doesn't support to list snippets. It has no show on the completion popup menu the snips candidates.

Is there a way to achive this?

**Comment by ajh17** [comment]
Possible dup of #12.

Unless snippets are somehow built in to Vim, I will not change VCM to support them. Again, VCM will only offer the default `:help ins-completion` types offered by Vim defaults.

**Comment by tuyenpm9** [comment]
I have a question: Will this plugin list all possible snips for a patern?

For i.e: When user type `def`, previously as I remember with Ultisnips and completor.vim, I'd have `def` and `defn` to trigger snips. But I only get `def` in pop-up menu when using VCM. But I'm not for sure.

**Comment by ajh17** [comment]
No, unless snippet engines offer the completion in a completefunc or omnifunc. I'm not really familiar with how snippet engines offer the completion, as I don't use them, so my cautious answer is no.

I repeat, VCM will *only* offer the default `:help ins-completion` types offered by Vim defaults.
