### ISSUE TITLE
Required vim compiled with +python

### ISSUE THREAD

**Issue by SiliconKite** [ajh17/VimCompletesMe#59]
Hello,
When using the omnicomplete on a python method I get an "error : Required vim compiled with +python". Note that path autocompletion is working fine

Doing a vim --version I get the following
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  2 2017 11:16:01)
Included patches: 1-1171
Huge version with GTK3 GUI.  Features included (+) or not (-):
[...]
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
[...]

```
Weird thing is that, inside vim, I do a ":echo has ('python')" a get a 0. For ":echo has ('python3')" a get a 1. Any pointers to what I should check next?

Thanks

**Comment by ajh17** [comment]
This isn't related to VimCompletesMe.

I think what you're running into is an older version of the pythoncomplete.vim that is shipped with him. Please update to the latest vim, it should fix that issue.

**Comment by ajh17** [comment]
Alternatively, you can also, in a `~/.vim/after/ftplugin/python.vim`, ensure that the omnifunc is set to the python3 version like so:

```vim
if has("python3")
  setlocal omnifunc=python3complete#Complete
elseif has("python")
  setlocal omnifunc=pythoncomplete#Complete
endif
```
