### ISSUE TITLE
Cannot open /tmp/.mount_nvim*/usr/share/nvim/runtime/doc/tags for writing

### ISSUE THREAD

**Issue by ashish28ranjan** [ajh17/VimCompletesMe#60]
I am unable to generate helptags. When I write :helptags ALL, I get the following error

E152: Cannot open /tmp/.mount_nvimDMeFAN/usr/share/nvim/runtime/doc/tags for writing 

1. The folder .mount_nvimDMeFAN does not exist in /tmp.
2. The unique string after .mount_nvim changes everytime I open nvim. Will I have to run :helptags ALL everytime I open nvim?

**Comment by ajh17** [comment]
This has nothing at all to do with VimCompletesMe. This is something to do with your OS/vim configuration.
