### ISSUE TITLE
Tab not respecting completeopt "longest" or "noselect"

### ISSUE THREAD

**Issue by futurityverb** [ajh17/VimCompletesMe#61]
I believe I've narrowed this down to being an issue with VimCompletesMe, but please correct me if I'm mistaken.

Relevant configuration:

```
let g:vcm_direction = 'p'
set completeopt=menu,menuone,longest,preview,noselect
```

#### Omnicomplete behavior (expected):
```
$this->me<C-x><C-o>
```
results in:
```
$this->method
     | method1 |
     | method2 |
```
and pressing `<C-p>` results in:
```
$this->method2
     | method1 |
     |[method2]|
```

#### VimCompletesMe behavior:
```
$this->me<Tab>
```
results in:
```
$this->method2
     | method1 |
     |[method2]|
```

Am I missing something here?

**Comment by ajh17** [comment]
Yep, that's a bug. I'll take a look at it, thanks!
