### ISSUE TITLE
Preview when only one match.

### ISSUE THREAD

**Issue by bwmarrin** [ajh17/VimCompletesMe#62]
I've been using YCM for awhile and one thing I wish it would do, is provide the preview and scratch window when there is only one match. A lot of times either I write enough of a name that there's only one option or the struct/object only has one option.  So it just completes it.  But I don't get the scratch window showing the function definition - which I often need to know.

If there's multiple possible matches then the preview and scratch window show up as expected.

**Comment by ajh17** [comment]
You can try setting the “menuone” option for completeopt:

`set completeopt+=menuone`

**Comment by bwmarrin** [comment]
That does it :) Thanks a lot @ajh17
