### ISSUE TITLE
Tab not working out of the box

### ISSUE THREAD

**Issue by drjosephliu** [ajh17/VimCompletesMe#63]
I've read some of the other issues related to this. 

Things I've done:

1) Type a couple of letters and press Tab. All it does it add spaces.
2) `:verbose imap <Tab>` returns 'No mapping found'.

How do I get this plugin to work?

**Comment by ajh17** [comment]
Hi, can you explain how you installed the plugin and where this plugin's directory lives inside your ~/.vim folder?

**Comment by drjosephliu** [comment]
Hey I've actually managed to get it working now. Turns out I didn't install it properly the first time. As a side note though, once the autocomplete options pop-up, is there a way to rebind the scroll up/down keys to "j" and "k"? At the moment I can only scroll down by pressing tab

**Comment by ajh17** [comment]
No, that does not make sense, what if you want to enter an actual j or k character? 

Either way, the way to re-map scrolling through items in the popup menu is given by `:h ins-completion-menu`

Closing as this is not related to VCM
