### ISSUE TITLE
User-defined completion key?

### ISSUE THREAD

**Issue by la-la-lasagna** [ajh17/VimCompletesMe#67]
Hello VCM devs,

I (along with many others I think) have mapped Tab as my exit to normal mode from all other modes.  I have mapped my (vim-provided) autocomplete to \<Nul\>, i.e. Ctrl-Space.  I was trying to alter your plugin so that \<Nul\> was used instead of \<Tab\>.

 59 " Tab exits vi modes to normal mode.                                             
 60 nnoremap \<Tab> \<Esc\>                                                             
 61 vnoremap \<Tab> \<Esc\>gV                                                           
 62 onoremap \<Tab> \<Esc\>                                                             
 63 cnoremap \<Tab> \<C-C\>\<Esc\>                                                        
 64 inoremap \<Tab> \<Esc\>`^ 

209 " Use VIM auto complete with Ctrl-n remapped to Ctrl-Spc.  
210 inoremap <Nul> <C-n>   

I do not have experience making vim plugins, and so have some concerns with this fix, which basically just involved altering the imaps in plugin/VimCompletesMe.vim:

 30   "imap \<Tab\>   \<plug\>vim_completes_me_forward                                   
 31   "imap \<S-Tab\> \<plug\>vim_completes_me_backward                                  
 32   imap \<Nul\>   \<plug\>vim_completes_me_forward                                    
 33   imap \<S-Nul\> \<plug\>vim_completes_me_backward   

Concerns:
- in the autoload/VimCompletesMe.vim \<Tab\> is used at one point and I am not sure if this will cause issues.
- \<S-Nul\> may not exist as a legal mapping: it seems to default to regular imode tabbing as I have seen by printing within autoload/VimCompletesMe.vim.
- Not sure how you are accessing vim's built-in functionality and/or how to properly re-map that functionality's use of Tab with Nul.

Thus, I ask you if it is at all possible to make this plugin have a variable which the user can reset within the vimrc which is initially Tab.

Thanks, and have a good day!

**Comment by ajh17** [comment]
This is already possible with https://github.com/ajh17/VimCompletesMe/blob/master/doc/VimCompletesMe.txt#L131

If you set the above variable to 0, you can provide your own maps in your ~/.vimrc for `vim_completes_me_forward` and `vim_completes_me_backward`.

Feel free to re-open if you're having issues with the above.
