### ISSUE TITLE
No tag completion (</)

### ISSUE THREAD

**Issue by wizardlink** [ajh17/VimCompletesMe#68]
Basically I am writing a `react` (JSX -> Javascript + HTML) app in which I am trying to complete an HTML tag. By hitting the default key (tab) it will try to look for a directory but if I do a manual Omni completion it does completes the tag normally.

For context:
![image](https://user-images.githubusercontent.com/26727907/72291411-106a0300-362e-11ea-8b69-ddc752b08df9.png)
![image](https://user-images.githubusercontent.com/26727907/72291422-165fe400-362e-11ea-808b-60f7ee278bcd.png)

Although if I start typing the tag's name it does gives me a suggestion. Not sure if it is intended but being used to just typing just `</` and omni completing, having to put the beginning of the tag name can be bothersome at times.

**Comment by ajh17** [comment]
This is working as designed. VCM will choose file path completion if it notices a forward slash (backslash in windows).

You can tweak VCM's omnicompletion detector by adding the `</` string to the the `b:vcm_omni_pattern` variable. Here's the [doc](https://github.com/ajh17/VimCompletesMe/blob/master/doc/VimCompletesMe.txt#L149) for that.

**Comment by wizardlink** [comment]
I see... Thank you @ajh17! I will take a look into it.
