### ISSUE TITLE
How prevent <CR> selection in popup from entering a new line?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [ajh17/VimCompletesMe#71]
Yep, just as @sunaku said.

If you want `<CR>` to select a completion entry instead, you can map CR to: 

`inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"`

_Originally posted by @ajh17 in https://github.com/ajh17/VimCompletesMe/issues/13#issuecomment-94191030_

-----

Hello Akshay! 

Whenever I use <CR> to make a selection from VCM's popup window, the proper text will be added, but vim will also create a new line with the cursor ready to go from that new position.

For example, say I select 'text' from the below position (cursor position denoted as `|`)
```
This is some example te|
```
When I select 'text' from the popup, it results in
```
This is some example text
|
```
(Note the new line created with the cursor at the start of that new line)

How can I have it, instead, insert the text and place cursor at the end of the word without creating a new line?

Thank you for the great plugin!

**Comment by ajh17** [comment]
Hey!

Sorry for the delay in replying. Are you using the Enter key to select the item? The normal Vim way to do this is by pressing `Ctrl-y` (See `:help complete_CTRL-Y`) while the popup menu is active. Otherwise, if you want to use the Enter key to select the popup entry, my earlier comment in #13 should help.

Are you having any issues with this mapping?

**Comment by Blake-LeBlanc** [comment]
> Hey!
> 
> Sorry for the delay in replying. Are you using the Enter key to select the item? The normal Vim way to do this is by pressing `Ctrl-y` (See `:help complete_CTRL-Y`) while the popup menu is active. Otherwise, if you want to use the Enter key to select the popup entry, my earlier comment in #13 should help.
> 
> Are you having any issues with this mapping?

Thank you for getting back to me Akshay! 

Sorry, I forgot to update my post over here once I figured it out.

Turns out the behavior was caused by a conflicting auto-pairs plugin (Lexima). 

Thanks again!
