### ISSUE TITLE
How to use the plugin in vim7.3

### ISSUE THREAD

**Issue by xuzhenyu69** [ajh17/VimCompletesMe#72]

**Comment by ajh17** [comment]
I would actually not recommend you install any plugins before you learn how to do that yourself.

Plugins get in the way of learning how to use Vim properly. Once you go through `vimtutor`, go through `:help usr_05` inside Vim itself, and it'll walk you through the different ways of installation.

Good luck!

**Comment by aemonge** [comment]
You can also learn vim thought a fun game -> https://vim-adventures.com/
