### ISSUE TITLE
E216: No such group or event: CompleteDone

### ISSUE THREAD

**Issue by ajh17** [ajh17/VimCompletesMe#9]
CompleteDone was introduced with a later vim7.3 patch.

Improve this so VimCompletesMe supports Vim 7.3.0

**Comment by jonthn** [comment]
Quick information for those that face this problem you should check if you have the 'patch598' (see https://groups.google.com/forum/#!searchin/vim_dev/598/vim_dev/XDFDQ8rkBII/xfOjjDzpa00J)

**Comment by ajh17** [comment]
@jonthn Thanks so much for the patch number and vim_dev link. I procrastinated on the search to find which patch introduced the CompleteDone event. :sweat_smile:

The issue should not be fixed.

**Comment by jonthn** [comment]
No problem it's my pleasure to help.
Thanks for your plugin btw :)

**Comment by ajh17** [comment]
:+1:
